nodeLinker: pnp

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.3.0.cjs

httpsProxy: http://127.0.0.1:7890
